version: 2
updates:
  # Keep npm dependencies in the app up to date
  - package-ecosystem: "npm"
    directory: "/" # package.json is in Image-Generation-Tool root (this .github folder is inside it)
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "deps(npm)"
      include: "scope"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/" # monitors workflows in .github/workflows
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "deps(actions)"
      include: "scope"
