# Cloud Build config for deploying the Image Generation Tool static site to GCS
# Repository: https://github.com/ImNiall/Image-Generation-Tool
# Assumes package.json is at repo root and Vite outputs to dist/

steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  # Build the production bundle
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Sync the built assets to your GCS bucket used for website hosting
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', 'dist', 'gs://theinstructorshub.co.uk']

options:
  logging: CLOUD_LOGGING_ONLY
