[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "api"

[build.environment]
  # No longer need to omit API keys since they're now server-side only
  NODE_VERSION = "18"
