name: gitleaks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  scan:
    name: Run gitleaks secret scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # full history for accurate scanning

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --redact --no-banner
